name: Code Review
'on':
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | sh
      - name: Run ollama
        run: |
          ollama serve &
          ollama pull deepseek-r1:14b
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Code Review
        run: |
          git checkout ${{ github.base_ref }}
          git pull
          command="ollama run llama3.2:latest"
          git checkout ${{ github.head_ref }}
          echo "Reviewing Pull Request for branch $(git branch --show) : "
          mycode=$(git diff ${{ github.base_ref }})
          $command "Review this code: $review code. ОТВЕТ НА РУССКОМ ЯЗЫКЕ. Answer in russian language."